const translations = {
    es: {
        "header_title": "Robles Penthouse",
        "header_subtitle": "Lujo, Vista y Confort en lo más alto de San Gil",
        "nav_about": "Acerca",
        "nav_services": "Servicios",
        "nav_spaces": "Otros Espacios",
        "nav_popular": "Servicios Populares",
        "nav_rules": "Normas",
        "nav_info": "Información",
        "nav_location": "Ubicación",
        "nav_special": "¿Por qué es especial?",
        "nav_book": "Reserva aqui!!!",
        "virtual_tour_title": "Tour Virtual",
        "virtual_tour_subtitle": "Conoce nuestro espacio",
        "virtual_tour_desc": "Vive San Gil desde las alturas. Descubre el encanto del Robles Penthouse, un alojamiento exclusivo ubicado en San Gil, la capital turística de Santander. Sumérgete en un entorno natural lleno de aventura, cultura y paisajes inolvidables. Disfruta de una vista privilegiada, comodidad excepcional y acceso a los principales destinos turísticos de la región.¡Haz tu reserva hoy y prepárate para una experiencia única en el corazón de Colombia!",
        "penthouse_title": "PENTHOUSE con terraza privada en la azotea y vistas panoramicas",
        "penthouse_desc": "Robles Penthouse se destaca por su ubicación privilegiada en las afueras de San Gil, con una vista panorámica incomparable. Su diseño moderno y elegante, junto con un jacuzzi privado, hacen de este alojamiento un lugar exclusivo para descansar y disfrutar. Además, ofrece espacios acogedores, servicios de alta calidad, fácil acceso a atracciones turísticas y una experiencia pensada para quienes buscan confort, privacidad y un ambiente inolvidable.",
        "form_title": "Verificar disponibilidad y precios",
        "form_arrival": "Fecha de entrada",
        "form_departure": "Fecha de salida",
        "form_guests": "Número de huéspedes (Max. 5)",
        "form_name": "Nombre Completo:",
        "form_name_placeholder": "Ingresa tu nombre completo",
        "form_phone": "Teléfono / WhatsApp:",
        "form_phone_placeholder": "Para contactarte",
        "form_submit": "Consultar disponibilidad y reservar",
        "success_title": "¡Solicitud Enviada!",
        "success_desc": "Hemos recibido tu solicitud. Te contactaremos pronto al WhatsApp para confirmar.",
        "success_btn": "Seguir Navegando",
        "services_title": "Servicios",
        "service_kitchen": "Cocina Equipada",
        "service_washer": "Lavadora",
        "service_dryer": "Secadora",
        "service_jacuzzi": "Jacuzzi",
        "service_tv": "Smart TV",
        "service_bathroom": "Baño Privado",
        "service_ac": "Aire Acondicionado",
        "service_minibar": "Mini Bar",
        "spaces_title": "Otros Espacios",
        "spaces_desc": "Sala, baño inteligente, terraza comedor, zona karaoke, jardin natural y un ambiente acogedor y privado",
        "popular_title": "Servicios Populares",
        "popular_parking": "Parqueadero",
        "popular_wifi": "wifi",
        "popular_dishes": "Vajilla y Cubierteria",
        "popular_views": "Vista Panoramica",
        "rules_title": "Normas del Alojamiento",
        "rule_header_name": "Norma",
        "rule_header_desc": "Descripción",
        "rule_checkin_name": "Check-in",
        "rule_checkin_desc": "Desde las 15:00",
        "rule_checkout_name": "Check-out",
        "rule_checkout_desc": "Antes de las 12:00",
        "rule_minors_name": "Menores de edad",
        "rule_minors_desc": "No se admiten menores de edad, ya que las instalaciones no se encuentran adecuadas",
        "rule_pets_name": "Mascotas",
        "rule_pets_desc": "No estan permitidas las mascotas",
        "info_title": "Información Importante",
        "info_desc": "Recomendaciones de seguridad, contacto de emergencia, y más.",
        "info_item_1": "Se encuentra en un 5 piso, por lo que hay que subir escaleras",
        "info_item_2": "Actualmente se estan adelantando obras en los pisos inferiores de 07:00 a 17:00",
        "info_item_3": "Posibilidad de entrada/salida flexible (previa coordinación)",
        "location_nearby": "Cerca de la Ubicación",
        "nearby_restaurant": "Restaurante",
        "nearby_water": "Deportes Acuaticos",
        "nearby_paragliding": "Parapente",
        "special_title": "¿Qué hace especial a este alojamiento?",
        "special_desc_1": "Robles Penthouse te ofrece una experiencia de lujo y confort, este exclusivo penthouse cuenta con:",
        "special_item_1": "Habitaciones con baño privado",
        "special_item_2": "Baño inteligente con funciones modernas",
        "special_item_3": "Duchas con agua caliente",
        "special_item_4": "Cocina completamente equipada",
        "special_item_5": "Sala de estar interior y comedor exterior",
        "special_item_6": "Minibar con sistema de karaoke",
        "special_item_7": "Espacios diseñados para el descanso y el entretenimiento",
        "special_desc_2": "Ideal para escapadas románticas, celebraciones especiales o simplemente para disfrutar del estilo de vida en lo más alto.",
        "special_welcome": "¡Bienvenidos a Robles Penthouse!",
        "special_experience": "Vive una experiencia de lujo y confort en las alturas.",
        "special_designed": "Este exclusivo penthouse está diseñado para quienes buscan un ambiente elegante, moderno y lleno de detalles únicos. Perfecto para escapadas románticas, celebraciones especiales o simplemente para relajarte con estilo.",
        "special_includes": "Incluye:",
        "special_inc_1": "Sala de estar exterior con calefactor y comedor al aire libre con vista panorámica",
        "special_inc_2": "Sala interior con televisor y un ambiente acogedor con vista a la ciudad",
        "special_inc_3": "Cocina totalmente equipada",
        "special_inc_4": "Lavadora-secadora incluida para que tu estadía sea agradable",
        "special_inc_5": "Servicio de minibar con sistema de karaoke para momentos inolvidables",
        "special_inc_6": "2 habitaciones, cada una con televisor, baño privado el cual cuenta con agua caliente y aire acondicionado",
        "special_inc_7": "Jacuzzi con acceso a un amplio balcón",
        "special_footer": "Déjate envolver por el encanto de un espacio creado para el descanso, el entretenimiento y el placer. Robles Penthouse: donde el lujo se encuentra con la comodidad.",
        "map_title": "Ubicación",
        "reviews_title": "Lo que dicen nuestros huéspedes",
        "reviews_date_1": "Julio 2024",
        "reviews_text_1": "\"Excelente lugar, con una vista espectacular, la mejor atención 10/10.\"",
        "reviews_date_2": "Noviembre 2025",
        "reviews_text_2": "\"Everything to be honest... Excellent place / apartment, easily fits 4 people, a family. Everything is done to high specs / modern ...amazing views of the town and more .. excellent facilities .. the staff were exceptional.. friendly , and attentive. Also flexible with any requests .. breakfast was delicious , 3 options to choose from ... Location is great.. outskirts of town , easy 5 mins taxi or can walk ...If I would go to San Gill I would definitely go back .. actually it could even be a reason to go to San Gill .. apart from nature / activities\"",
        "reviews_date_3": "Septiembre 2025",
        "reviews_text_3": "\"Nuestra estancia ha sido simplemente maravillosa. Desde el primer momento me encantó el ambiente acogedor, las vistas espectaculares y la tranquilidad que transmite el lugar. La casa está decorada con mucho gusto y cada detalle invita a relajarse y disfrutar. Me gustó tanto la experiencia que decidí quedarme una noche más, porque realmente es un sitio que invita a prolongar la estancia.\"",
        "google_reviews": "Ver todas las reseñas en Google",
        "footer_rights": "© 2025 Robles Penthouse. Todos los derechos reservados",
        "footer_contact": "Contáctenos:",
        "error_dates_booked_title": "Lo sentimos",
        "error_dates_booked": "Lo sentimos, estas fechas están reservadas en otra plataforma (Airbnb/Booking). Por favor elige otros días.",
        "contact_title": "Contáctanos",
        "contact_back": "← Volver al Inicio",
        "contact_label_name": "Nombre:",
        "contact_label_lastname": "Apellido:",
        "contact_label_email": "Correo Electrónico:",
        "contact_label_phone": "Teléfono:",
        "contact_label_subject": "Asunto:",
        "contact_subject_placeholder": "Selecciona un tema",
        "contact_subject_reserva": "Reserva",
        "contact_subject_queja": "Queja o reclamo",
        "contact_subject_sugerencia": "Sugerencia",
        "contact_subject_informacion": "Pregunta General / Información",
        "contact_subject_colaboracion": "Propuesta de Colaboración",
        "contact_subject_feedback": "Comentarios sobre mi Estancia",
        "contact_subject_billing": "Solicitud de Facturacion Electrónica",
        "contact_label_message": "Mensaje:",
        "contact_message_placeholder": "Escribe tu mensaje aquí...",
        "contact_rating_title": "¿Cómo calificarías tu experiencia?",
        "contact_submit": "Enviar mensaje"
    },
    en: {
        "header_title": "Robles Penthouse",
        "header_subtitle": "Luxury, Panoramic Views & Comfort in the Heights of San Gil",
        "nav_about": "About",
        "nav_services": "Services",
        "nav_spaces": "Amenities",
        "nav_popular": "Popular Amenities",
        "nav_rules": "Guidelines",
        "nav_info": "Information",
        "nav_location": "Location",
        "nav_special": "The Experience",
        "nav_book": "Book Now!",
        "virtual_tour_title": "Virtual Tour",
        "virtual_tour_subtitle": "Discover Our Sanctuary",
        "virtual_tour_desc": "Experience San Gil from above. Discover the charm of Robles Penthouse, an exclusive getaway located in the tourism capital of Santander. Immerse yourself in a natural environment full of adventure, culture, and unforgettable landscapes. Enjoy a privileged view, exceptional comfort, and easy access to the region's main attractions. Book your stay today and prepare for a unique experience in the heart of Colombia!",
        "penthouse_title": "PENTHOUSE with Private Rooftop Terrace & Panoramic Views",
        "penthouse_desc": "Robles Penthouse stands out for its privileged location on the outskirts of San Gil, offering an incomparable panoramic view. Its modern and elegant design, combined with a private jacuzzi, makes this stay an exclusive place to rest and recharge. Furthermore, it offers cozy living spaces, high-quality services, easy access to tourist attractions, and an experience designed for those seeking comfort, privacy, and an unforgettable atmosphere.",
        "form_title": "Check Availability & Premium Pricing",
        "form_arrival": "Arrival Date",
        "form_departure": "Departure Date",
        "form_guests": "Number of Guests (Max. 5)",
        "form_name": "Full Name:",
        "form_name_placeholder": "Enter your full name",
        "form_phone": "Phone / WhatsApp:",
        "form_phone_placeholder": "How can we reach you?",
        "form_submit": "Check Availability & Request Booking",
        "success_title": "Request Submitted!",
        "success_desc": "We have received your request. We will contact you shortly via WhatsApp to confirm your stay.",
        "success_btn": "Continue Browsing",
        "services_title": "Boutique Services",
        "service_kitchen": "Fully Equipped Kitchen",
        "service_washer": "Private Laundry",
        "service_dryer": "Drying Facilities",
        "service_jacuzzi": "Private Jacuzzi",
        "service_tv": "Smart Entertainment",
        "service_bathroom": "Master Ensuite",
        "service_ac": "Climate Control",
        "service_minibar": "Premium Mini Bar",
        "spaces_title": "Living Spaces",
        "spaces_desc": "Elegant living room, smart bathroom, al fresco dining terrace, karaoke lounge, natural garden, and a private, sophisticated atmosphere.",
        "popular_title": "Curated Amenities",
        "popular_parking": "Secure Parking",
        "popular_wifi": "High-Speed connectivity",
        "popular_dishes": "Fine China & Silverware",
        "popular_views": "Iconic Skyline Views",
        "rules_title": "Guest Guidelines",
        "rule_header_name": "Policy",
        "rule_header_desc": "Details",
        "rule_checkin_name": "Check-in",
        "rule_checkin_desc": "After 15:00",
        "rule_checkout_name": "Check-out",
        "rule_checkout_desc": "Before 12:00",
        "rule_minors_name": "Children & Minors",
        "rule_minors_desc": "Adults only; facilities are not suitable for minors.",
        "rule_pets_name": "Pet Policy",
        "rule_pets_desc": "Pets are not permitted to ensure a serene environment.",
        "info_title": "Essential Information",
        "info_desc": "Safety protocols, emergency contacts, and guest recommendations.",
        "info_item_1": "Located on the 5th floor; stair access required.",
        "info_item_2": "Maintenance works are ongoing in lower floors from 07:00 to 17:00.",
        "info_item_3": "Flexible arrival/departure options available upon prior coordination.",
        "location_nearby": "Local Attractions",
        "nearby_restaurant": "Gourmet Dining",
        "nearby_water": "Water Activities",
        "nearby_paragliding": "Paragliding Adventures",
        "special_title": "What Makes Your Stay Exceptional?",
        "special_desc_1": "Robles Penthouse offers an experience of luxury and comfort. This exclusive residence features:",
        "special_item_1": "Private ensuite bathrooms",
        "special_item_2": "State-of-the-art smart bathroom features",
        "special_item_3": "Premium hot water showers",
        "special_item_4": "Gourmet chef's kitchen",
        "special_item_5": "Sophisticated indoor lounge and outdoor dining area",
        "special_item_6": "Mini-bar with professional karaoke system",
        "special_item_7": "Desiger spaces for relaxation and entertainment",
        "special_desc_2": "Ideally curated for romantic getaways, exclusive celebrations, or simply indulging in a high-tier lifestyle.",
        "special_welcome": "Welcome to Robles Penthouse!",
        "special_experience": "A Masterclass in High-Altitude Luxury & Comfort.",
        "special_designed": "This exclusive penthouse is crafted for those seeking an elegant, modern environment rich in unique details. Perfect for romantic journeys, special milestones, or simply relaxing with distinction.",
        "special_includes": "Key Features:",
        "special_inc_1": "Outdoor terrace with heater and al fresco dining with panoramic cityscape",
        "special_inc_2": "Indoor lounge with premium TV and a cozy, city-view atmosphere",
        "special_inc_3": "Fully equipped gourmet kitchen",
        "special_inc_4": "In-unit washer and dryer for your convenience",
        "special_inc_5": "Custom mini-bar and entertainment system",
        "special_inc_6": "2 luxurious bedrooms with climate control and private ensuites",
        "special_inc_7": "Private Jacuzzi overlooking the grand balcony",
        "special_footer": "Surrender to the charm of a space created for ultimate relaxation and pleasure. Robles Penthouse: where luxury meets convenience.",
        "map_title": "Prime Location",
        "reviews_title": "Words from Our Guests",
        "reviews_date_1": "July 2024",
        "reviews_text_1": "\"Excellent place with an amazing view, top-tier service 10/10.\"",
        "reviews_date_2": "November 2025",
        "reviews_text_2": "\"Everything to be honest... Excellent place / apartment, easily fits 4 people, a family. Everything is done to high specs / modern ...amazing views of the town and more .. excellent facilities .. the staff were exceptional.. friendly , and attentive. Also flexible with any requests .. breakfast was delicious , 3 options to choose from ... Location is great.. outskirts of town , easy 5 mins taxi or can walk ...If I would go to San Gill I would definitely go back .. actually it could even be a reason to go to San Gill .. apart from nature / activities\"",
        "reviews_date_3": "September 2025",
        "reviews_text_3": "\"Our stay was simply wonderful. From the very first moment, I loved the cozy atmosphere, the spectacular views, and the tranquility. The house is tastefully decorated and every detail invites you to relax. I enjoyed it so much that I extended my stay for another night.\"",
        "google_reviews": "View all Guest Reviews on Google",
        "footer_rights": "© 2025 Robles Penthouse. All rights reserved",
        "footer_contact": "Contact Us:",
        "error_dates_booked_title": "We are sorry",
        "error_dates_booked": "We're sorry, these dates are reserved on another platform (Airbnb/Booking). Please select alternative dates.",
        "contact_title": "Reach Out to Us",
        "contact_back": "← Back to Home",
        "contact_label_name": "First Name:",
        "contact_label_lastname": "Last Name:",
        "contact_label_email": "Email Address:",
        "contact_label_phone": "Phone Number:",
        "contact_label_subject": "Subject:",
        "contact_subject_placeholder": "Select an inquiry type",
        "contact_subject_reserva": "Booking Request",
        "contact_subject_queja": "Feedback & Concerns",
        "contact_subject_sugerencia": "Suggestions",
        "contact_subject_informacion": "General Inquiries",
        "contact_subject_colaboracion": "Partnership Proposals",
        "contact_subject_feedback": "Guest Feedback",
        "contact_subject_billing": "Electronic Invoicing Request",
        "contact_label_message": "Message Body:",
        "contact_message_placeholder": "How can we assist you?",
        "contact_rating_title": "How would you rate your experience?",
        "contact_submit": "Dispatch Message"
    }
};
